
package proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "BanqueService", targetNamespace = "http://webservice/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface BanqueService {


    /**
     * @return returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://webservice/", className = "proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://webservice/", className = "proxy.ListComptesResponse")
    @Action(input = "http://webservice/BanqueService/listComptesRequest", output = "http://webservice/BanqueService/listComptesResponse")
    public List<Compte> listComptes();

    /**
     * @param montant
     * @return returns double
     */
    @WebMethod(operationName = "ConversionEurotoDH")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEurotoDH", targetNamespace = "http://webservice/", className = "proxy.ConversionEurotoDH")
    @ResponseWrapper(localName = "ConversionEurotoDHResponse", targetNamespace = "http://webservice/", className = "proxy.ConversionEurotoDHResponse")
    @Action(input = "http://webservice/BanqueService/ConversionEurotoDHRequest", output = "http://webservice/BanqueService/ConversionEurotoDHResponse")
    public double conversionEurotoDH(
            @WebParam(name = "montant", targetNamespace = "")
                    double montant);

    /**
     * @param code
     * @return returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://webservice/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://webservice/", className = "proxy.GetCompteResponse")
    @Action(input = "http://webservice/BanqueService/getCompteRequest", output = "http://webservice/BanqueService/getCompteResponse")
    public Compte getCompte(
            @WebParam(name = "code", targetNamespace = "")
                    Long code);

}
